version: '3'

services:
  rabbit:
    image: rabbitmq:3-management
    hostname: rabbit
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
      - "61613:61613"
    volumes:
      - ./rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins

  app:
    build: ./spring
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      - rabbit

  nginx:
    build:
      context: ./nginx
    restart: unless-stopped
    ports:
      - 80:80
    depends_on:
      - app